### ISSUE TITLE
Remove Replace Directive in go.mod to allow global installs using `go install`

### ISSUE THREAD

**Issue by teddyknox** [strangelove-ventures/heighliner#122]
I came across this while building a CircleCI workflow for building Duality. Heighliner is not a one-line install because of the replace directive here: https://github.com/strangelove-ventures/heighliner/blob/main/go.mod#L85

I'm not sure what it's for but if it were removed it would resolve this error:

```
➜  go install github.com/strangelove-ventures/heighliner@latest
go: github.com/strangelove-ventures/heighliner@latest (in github.com/strangelove-ventures/heighliner@v1.2.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by agouin** [comment]
Resolved in #173 

Released in [v1.4.1](https://github.com/strangelove-ventures/heighliner/releases/tag/v1.4.1)
