### ISSUE TITLE
CICD should lint the `chains.yaml` and fail if not valid

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/heighliner#131]
If the chains.yaml is malformed, heighliner will not work at all.

**Comment by danbryan** [comment]
maybe pre-commit to check chains.yaml ?  Maybe compare it against go structs

**Comment by DavidNix** [comment]
Simple yaml lint is the first pass. To cause it to break, make chains.yaml invalid - add some malformed data in there.
