### ISSUE TITLE
bug: when building the image by passing all overrides, not able to provide image name 

### ISSUE THREAD

**Issue by spoo-bar** [strangelove-ventures/heighliner#163]
Heighliner commit hash: `2da0b66a365ef9dfd58230f137473b1b264a4927`

### Steps to reproduce: 
Trying to build an Heighliner image of a chain which isn't part of the ./chains.yaml file by providing overrides. 

```sh
heighliner build --org archway-network --repo archway --dockerfile cosmos --build-target "make build" --build-env "BUILD_TAGS=muslc" --binaries "build/archwayd" --git-ref v3.0.0 --tag test
```
Alternatively, also tried the below command but still didn't work

```
heighliner build archway --org archway-network --repo archway --dockerfile cosmos --build-target "make build" --build-env "BUILD_TAGS=muslc" --binaries "build/archwayd" --git-ref v3.0.0 --tag test
```

### Actual behavior: 

The generated image name is `acrechain:test`, which is just the name of the first chain in the chains.yaml.

### Expected behavior:

Generate an image with the name `archway:test`. 

It would be quite useful to be able to provide custom names for the generated images.

### Relevant Trace:

```sh
Loaded chains from /mnt/c/code/heighliner/chains.yaml
Using local cosmos/native.Dockerfile
Go version from go.mod: 1.19, will build with version: 1.19.6 image: 1.19.6-alpine3.17
Building image from ref: v3.0.0, resulting docker image tags: +[acrechain:test]
```

**Comment by akc2267** [comment]
you just need to add "-c archway"

**Comment by spoo-bar** [comment]
Thank you!

I didnt realise that `-c` could be used as the help cmd says 
`-c, --chain string             Cosmos chain to build from chains.yaml` 
and archway wasnt in chains.yaml
