### ISSUE TITLE
cheqd artifact does not work

### ISSUE THREAD

**Issue by whalelephant** [strangelove-ventures/heighliner#166]
The cheqd binary seems to be have been built incorrectly. 

Inside the cheqd:v1.4.4 docker
```
~ $ which cheqd-noded
/bin/cheqd-noded
~ $ /bin/cheqd-noded
sh: /bin/cheqd-noded: not found
```
I looked at a similar [issue](https://github.com/onomyprotocol/onomy/pull/129/files) but the [Makefile](https://github.com/cheqd/cheqd-node/blob/f8d41e68f437b9aa5cf10ff275fbd6365b6541ec/Makefile#L112) already consumes env LDFLAGS

Help would be appreciated! thanks!

**Comment by agouin** [comment]
The makefile is consuming `LD_FLAGS`, but not `LDFLAGS`, which I'm guessing is the root cause here.

**Comment by whalelephant** [comment]
Thanks @agouin!
