### ISSUE TITLE
osmosis - v20.2.1 - eip1559state.json :-(

### ISSUE THREAD

**Issue by PFC-developer** [strangelove-ventures/heighliner#197]
looks like osmosis v20.2.1 introduced a new feature (eip1559) which is attempting to write a file into the config/ directory.
(eip1559state.json).

I don't believe there is a config directive on where to store this. the sentry does start, but I assume it isn't performing as designed.

just a heads up for now.. hoping they will provide a config directive to put this into a /tmp/ directory or somesuch

**Comment by agouin** [comment]
This should be possible depending on your container orchestration. I don't believe it requires any changes to heighliner. For example: mounting a PVC to the necessary path should resolve this.
