### ISSUE TITLE
Add arm64 images

### ISSUE THREAD

**Issue by agouin** [strangelove-ventures/heighliner#2]
Helpful for development on m1 macs and deployment to hardware such as AWS Graviton

**Comment by DavidNix** [comment]
@agouin I'm on arm64 (m1 mac). 

The `gaia` container is giving me trouble with `musl`.

```bash
❯ docker run -it ghcr.io/strangelove-ventures/heighliner/gaia:v6.0.4 sh
~ # gaiad
qemu-x86_64: Could not open '/lib/ld-musl-x86_64.so.1': No such file or directory
~ # gaiad -h
qemu-x86_64: Could not open '/lib/ld-musl-x86_64.so.1': No such file or directory
~ #
```

Apologies if this is a known issue. 

The failure also happens in ibctest. My workaround is to use juno and osmosis which do not exhibit this issue. 

Also, if this should be a separate GH issue with a bug label, let me know!

**Comment by agouin** [comment]
Thanks @DavidNix for finding this and helping me troubleshoot. I found out that the `build-linux` target we are using for `gaia` is overwriting the `GOARCH` to `amd64`. This is fixed by using the `build` target instead.

**Comment by agouin** [comment]
The dockerfiles have been moved [here](https://github.com/strangelove-ventures/heighliner/tree/main/dockerfile).
All dockerfiles have been updated to cross compile using the host architecture for the build phase, then package the cross compiled binary into the final image with the target architecture in the last qemu step.

[Buildkit](https://github.com/moby/buildkit) integration was added [here](https://github.com/strangelove-ventures/heighliner/blob/main/docker/buildkit.go) so that CI and local can build the multi-arch images.

`chains.yaml` has been modified so that all chains will use a make target or build script that allows for cross-compilation
