### ISSUE TITLE
Support go v1.23

### ISSUE THREAD

**Issue by SpicyLemon** [strangelove-ventures/heighliner#270]
## Summary

Add support for golang v 1.23.

## Details

Go v1.23 was released mid August 2024 and the SDK has updated their `go.mod` (on `main`) to use it. This also means that now, go v1.21 and earlier are no longer maintained.

**Comment by vimystic** [comment]
Hi @SpicyLemon. We now support 1.23 for building image.
https://github.com/strangelove-ventures/heighliner/blob/89426ba941097466e63189457bb8a07666aacff9/builder/go_versions.go#L17

Closing this issue.Please reopen if you think i misinterpreted it.
