### ISSUE TITLE
Heighliner hardcodes wasm lib version

### ISSUE THREAD

**Issue by misko9** [strangelove-ventures/heighliner#49]
While using the latest version of Juno in IbcTest, the nodes failed to start with the following log:
Error: libwasmversion mismatch. got: 1.0.0; expected: v1.1.1

If the chain uses wasm, heighliner should query and download the correct version of wasmvm.

**Comment by 7AC** [comment]
I see a different flavor of this with the latest osmosis: https://github.com/strangelove-ventures/heighliner/pkgs/container/heighliner%2Fosmosis/103650535?tag=v15.1.2

```
Error: libwasmversion mismatch. got: 1.1.1; expected: v1.1.2
```
