### ISSUE TITLE
Axelar switched to go1.19

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/heighliner#90]
> @Validator Hey folks, we have switched to building axelard with go 1.19. Please update your build process to use that if you aren't already on it. You can test it out on the main branch: https://github.com/axelarnetwork/axelar-core
The upcoming release (tentatively planned for Tuesday, more details to come) will be using go 1.19

https://discord.com/channels/770814806105128977/869603957360713778/1075560955699810324

**Comment by agouin** [comment]
Heighliner automatically builds with the go version in go.mod, so this is covered automatically
